# This workflow will build, test and push the latest version on the beta environment.

on: 
  push:
    branches:
      - 'main'
          
name: 🔘 Test

jobs:
  deploy:
    name: test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
          
      ############################################
      # Install Java
      ###########################################      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      ############################################
      # Install Maven dependency submission
      ###########################################      
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.0
                  
      ############################################
      # Maven build and testing
      ###########################################    
                
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots install
                
