# This workflow will build, test and push the latest version on the beta environment.

on: 
  push:
    branches:
      - 'main'
          
name: 🔘 Test

jobs:
  deploy:
    name: test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
          
      ############################################
      # Install Java
      ###########################################      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'



# TODO : Put back, but bug with subfolders lprojetct layout
#      ############################################
#      # Install Maven dependency submission
#      ###########################################      
#      - name: Maven Dependency Tree Dependency Submission
#        uses: advanced-security/maven-dependency-submission-action@v4.0.0
                  
      ############################################
      # Maven build and testing
      ###########################################    
                
      - name: Build and test with Maven
        working-directory: ./o4g-xwiki-springboot-starter      
        run: mvn --batch-mode --update-snapshots install
                
