
xwiki:
  baseUrl: https://wiki.nudger.fr
  password: couilledu22
  username: Tif
  httpsOnly: true
  

# manage stack trace in response error
server:
  error:
    include-stacktrace: never
  
  #media: json  
  #entryPoint: rest
  #wiki: xwiki

